# Site settings
title: Hemanth Koralla
email: hemanth.koralla@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Ann Arbor
state: MI
zip_code: 48197
country: United States of America

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/hemanthk101/
linkedin_url: https://www.linkedin.com/in/hemanthkoralla
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
style: compressed